/**
 * Industry presets - pre-optimized configurations for different sectors.
 * Each preset defines: terminology, dashboard widgets, default categories,
 * custom fields, theme colors, and feature flags.
 */

const PRESETS = {
  healthcare: {
    label: "Healthcare / Clinic",
    icon: "🏥",
    description: "Clinics, doctors, dentists, therapists, wellness centers",
    theme: {
      primaryColor: "#10b981",
      secondaryColor: "#06b6d4",
      accentColor: "#0ea5e9",
      sidebarColor: "#064e3b",
      theme: "emerald",
    },
    terminology: {
      customers: "Patients",
      customer: "Patient",
      products: "Medications",
      product: "Medication",
      services: "Treatments",
      service: "Treatment",
      invoices: "Bills",
      invoice: "Bill",
    },
    categories: [
      { name: "Consultations", type: "service", color: "#10b981" },
      { name: "Diagnostics", type: "service", color: "#06b6d4" },
      { name: "Procedures", type: "service", color: "#0ea5e9" },
      { name: "Medications", type: "product", color: "#22c55e" },
      { name: "Medical Supplies", type: "product", color: "#14b8a6" },
    ],
    custom_fields: [
      {
        entity_type: "customer",
        field_name: "date_of_birth",
        field_label: "Date of Birth",
        field_type: "date",
      },
      {
        entity_type: "customer",
        field_name: "blood_group",
        field_label: "Blood Group",
        field_type: "select",
        options: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"],
      },
      {
        entity_type: "customer",
        field_name: "allergies",
        field_label: "Allergies",
        field_type: "textarea",
      },
      {
        entity_type: "customer",
        field_name: "medical_history",
        field_label: "Medical History",
        field_type: "textarea",
      },
      {
        entity_type: "customer",
        field_name: "insurance_provider",
        field_label: "Insurance Provider",
        field_type: "text",
      },
    ],
    dashboard_widgets: [
      "appointments_today",
      "patients_total",
      "revenue_month",
      "pending_bills",
      "low_stock_meds",
    ],
    feature_flags: {
      appointments: true,
      prescriptions: true,
      lab_reports: true,
    },
  },

  engineering: {
    label: "Engineering / Construction",
    icon: "🏗️",
    description: "Engineering firms, construction, contractors, architects",
    theme: {
      primaryColor: "#f59e0b",
      secondaryColor: "#ef4444",
      accentColor: "#eab308",
      sidebarColor: "#451a03",
      theme: "amber",
    },
    terminology: {
      customers: "Clients",
      customer: "Client",
      products: "Materials",
      product: "Material",
      services: "Projects",
      service: "Project",
      invoices: "Estimates",
      invoice: "Estimate",
    },
    categories: [
      { name: "Civil", type: "service", color: "#f59e0b" },
      { name: "Mechanical", type: "service", color: "#ef4444" },
      { name: "Electrical", type: "service", color: "#eab308" },
      { name: "Raw Materials", type: "product", color: "#a3a3a3" },
      { name: "Equipment", type: "product", color: "#737373" },
    ],
    custom_fields: [
      {
        entity_type: "service",
        field_name: "project_code",
        field_label: "Project Code",
        field_type: "text",
      },
      {
        entity_type: "service",
        field_name: "site_location",
        field_label: "Site Location",
        field_type: "text",
      },
      {
        entity_type: "service",
        field_name: "start_date",
        field_label: "Start Date",
        field_type: "date",
      },
      {
        entity_type: "service",
        field_name: "completion_date",
        field_label: "Completion Date",
        field_type: "date",
      },
      {
        entity_type: "customer",
        field_name: "company_reg",
        field_label: "Company Registration",
        field_type: "text",
      },
    ],
    dashboard_widgets: [
      "active_projects",
      "pending_estimates",
      "revenue_month",
      "material_inventory",
      "team_workload",
    ],
    feature_flags: { projects: true, estimates: true, timesheet: true },
  },

  education: {
    label: "Teaching / Education",
    icon: "🎓",
    description: "Teachers, tutors, schools, training institutes",
    theme: {
      primaryColor: "#8b5cf6",
      secondaryColor: "#ec4899",
      accentColor: "#a855f7",
      sidebarColor: "#3b0764",
      theme: "violet",
    },
    terminology: {
      customers: "Students",
      customer: "Student",
      products: "Course Materials",
      product: "Material",
      services: "Courses",
      service: "Course",
      invoices: "Fee Invoices",
      invoice: "Fee Invoice",
    },
    categories: [
      { name: "Mathematics", type: "service", color: "#8b5cf6" },
      { name: "Science", type: "service", color: "#06b6d4" },
      { name: "Languages", type: "service", color: "#ec4899" },
      { name: "Textbooks", type: "product", color: "#f59e0b" },
      { name: "Stationery", type: "product", color: "#10b981" },
    ],
    custom_fields: [
      {
        entity_type: "customer",
        field_name: "grade_level",
        field_label: "Grade / Level",
        field_type: "text",
      },
      {
        entity_type: "customer",
        field_name: "parent_name",
        field_label: "Parent / Guardian Name",
        field_type: "text",
      },
      {
        entity_type: "customer",
        field_name: "parent_phone",
        field_label: "Parent Phone",
        field_type: "text",
      },
      {
        entity_type: "customer",
        field_name: "school",
        field_label: "School",
        field_type: "text",
      },
      {
        entity_type: "service",
        field_name: "schedule",
        field_label: "Schedule",
        field_type: "text",
      },
    ],
    dashboard_widgets: [
      "active_students",
      "courses_running",
      "fees_collected",
      "pending_fees",
      "attendance",
    ],
    feature_flags: { attendance: true, grades: true, schedule: true },
  },

  student: {
    label: "Student / Personal",
    icon: "📚",
    description: "Personal finance & study tracking for students",
    theme: {
      primaryColor: "#3b82f6",
      secondaryColor: "#8b5cf6",
      accentColor: "#06b6d4",
      sidebarColor: "#1e3a8a",
      theme: "blue",
    },
    terminology: {
      customers: "Contacts",
      customer: "Contact",
      products: "Items",
      product: "Item",
      services: "Tasks",
      service: "Task",
      invoices: "Expenses",
      invoice: "Expense",
    },
    categories: [
      { name: "Tuition", type: "service", color: "#3b82f6" },
      { name: "Books", type: "product", color: "#8b5cf6" },
      { name: "Food", type: "product", color: "#f59e0b" },
      { name: "Transport", type: "service", color: "#10b981" },
    ],
    custom_fields: [
      {
        entity_type: "service",
        field_name: "subject",
        field_label: "Subject",
        field_type: "text",
      },
      {
        entity_type: "service",
        field_name: "deadline",
        field_label: "Deadline",
        field_type: "date",
      },
    ],
    dashboard_widgets: [
      "monthly_expenses",
      "pending_tasks",
      "upcoming_deadlines",
      "savings",
    ],
    feature_flags: { budget: true, tasks: true },
  },

  sales: {
    label: "Sales / B2B",
    icon: "💼",
    description: "Sales teams, B2B reps, account managers, agencies",
    theme: {
      primaryColor: "#0ea5e9",
      secondaryColor: "#6366f1",
      accentColor: "#3b82f6",
      sidebarColor: "#0c4a6e",
      theme: "sky",
    },
    terminology: {
      customers: "Leads",
      customer: "Lead",
      products: "Products",
      product: "Product",
      services: "Packages",
      service: "Package",
      invoices: "Quotes",
      invoice: "Quote",
    },
    categories: [
      { name: "Hot Leads", type: "service", color: "#ef4444" },
      { name: "Warm Leads", type: "service", color: "#f59e0b" },
      { name: "Cold Leads", type: "service", color: "#06b6d4" },
      { name: "Subscription", type: "product", color: "#8b5cf6" },
    ],
    custom_fields: [
      {
        entity_type: "customer",
        field_name: "lead_source",
        field_label: "Lead Source",
        field_type: "select",
        options: [
          "Website",
          "Referral",
          "Cold Call",
          "Event",
          "Social Media",
          "Other",
        ],
      },
      {
        entity_type: "customer",
        field_name: "lead_stage",
        field_label: "Pipeline Stage",
        field_type: "select",
        options: [
          "New",
          "Contacted",
          "Qualified",
          "Proposal",
          "Negotiation",
          "Won",
          "Lost",
        ],
      },
      {
        entity_type: "customer",
        field_name: "deal_value",
        field_label: "Deal Value",
        field_type: "number",
      },
      {
        entity_type: "customer",
        field_name: "next_followup",
        field_label: "Next Follow-up",
        field_type: "date",
      },
    ],
    dashboard_widgets: [
      "pipeline_value",
      "leads_by_stage",
      "won_this_month",
      "conversion_rate",
      "followups_today",
    ],
    feature_flags: { pipeline: true, followups: true, deals: true },
  },

  retail: {
    label: "Retail / Shop",
    icon: "🛍️",
    description: "Shops, boutiques, grocery stores, retail outlets",
    theme: {
      primaryColor: "#ec4899",
      secondaryColor: "#f43f5e",
      accentColor: "#a855f7",
      sidebarColor: "#831843",
      theme: "pink",
    },
    terminology: {
      customers: "Customers",
      customer: "Customer",
      products: "Products",
      product: "Product",
      services: "Services",
      service: "Service",
      invoices: "Sales",
      invoice: "Sale",
    },
    categories: [
      { name: "General", type: "product", color: "#ec4899" },
      { name: "Featured", type: "product", color: "#a855f7" },
      { name: "Clearance", type: "product", color: "#ef4444" },
      { name: "New Arrivals", type: "product", color: "#10b981" },
    ],
    custom_fields: [
      {
        entity_type: "product",
        field_name: "brand",
        field_label: "Brand",
        field_type: "text",
      },
      {
        entity_type: "product",
        field_name: "size",
        field_label: "Size",
        field_type: "text",
      },
      {
        entity_type: "product",
        field_name: "color",
        field_label: "Color",
        field_type: "text",
      },
      {
        entity_type: "customer",
        field_name: "loyalty_points",
        field_label: "Loyalty Points",
        field_type: "number",
      },
    ],
    dashboard_widgets: [
      "sales_today",
      "top_products",
      "low_stock",
      "revenue_month",
      "customer_count",
    ],
    feature_flags: { pos: true, barcode: true, loyalty: true },
  },

  warehouse: {
    label: "Warehouse / Logistics",
    icon: "📦",
    description: "Warehouses, distributors, logistics, supply chain",
    theme: {
      primaryColor: "#64748b",
      secondaryColor: "#f59e0b",
      accentColor: "#3b82f6",
      sidebarColor: "#0f172a",
      theme: "slate",
    },
    terminology: {
      customers: "Vendors",
      customer: "Vendor",
      products: "Stock Items",
      product: "Stock Item",
      services: "Logistics",
      service: "Service",
      invoices: "Orders",
      invoice: "Order",
    },
    categories: [
      { name: "Raw Goods", type: "product", color: "#64748b" },
      { name: "Finished Goods", type: "product", color: "#10b981" },
      { name: "Packaging", type: "product", color: "#f59e0b" },
      { name: "Returns", type: "product", color: "#ef4444" },
    ],
    custom_fields: [
      {
        entity_type: "product",
        field_name: "warehouse_location",
        field_label: "Warehouse Location / Bin",
        field_type: "text",
      },
      {
        entity_type: "product",
        field_name: "supplier",
        field_label: "Supplier",
        field_type: "text",
      },
      {
        entity_type: "product",
        field_name: "reorder_point",
        field_label: "Reorder Point",
        field_type: "number",
      },
      {
        entity_type: "product",
        field_name: "expiry_date",
        field_label: "Expiry Date",
        field_type: "date",
      },
    ],
    dashboard_widgets: [
      "inventory_value",
      "low_stock_alerts",
      "incoming_shipments",
      "outgoing_today",
      "stock_movement",
    ],
    feature_flags: {
      multi_warehouse: true,
      batch_tracking: true,
      barcode: true,
    },
  },

  accounting: {
    label: "Accounting / Finance",
    icon: "📊",
    description: "Accountants, CPAs, bookkeepers, financial advisors",
    theme: {
      primaryColor: "#059669",
      secondaryColor: "#0891b2",
      accentColor: "#10b981",
      sidebarColor: "#022c22",
      theme: "green",
    },
    terminology: {
      customers: "Clients",
      customer: "Client",
      products: "Items",
      product: "Item",
      services: "Services",
      service: "Service",
      invoices: "Invoices",
      invoice: "Invoice",
    },
    categories: [
      { name: "Tax Filing", type: "service", color: "#059669" },
      { name: "Bookkeeping", type: "service", color: "#0891b2" },
      { name: "Audit", type: "service", color: "#8b5cf6" },
      { name: "Consulting", type: "service", color: "#f59e0b" },
    ],
    custom_fields: [
      {
        entity_type: "customer",
        field_name: "tax_id",
        field_label: "Tax ID / EIN",
        field_type: "text",
      },
      {
        entity_type: "customer",
        field_name: "fiscal_year_end",
        field_label: "Fiscal Year End",
        field_type: "date",
      },
      {
        entity_type: "customer",
        field_name: "entity_type",
        field_label: "Entity Type",
        field_type: "select",
        options: [
          "Individual",
          "LLC",
          "Corporation",
          "Partnership",
          "Non-Profit",
        ],
      },
    ],
    dashboard_widgets: [
      "revenue_month",
      "outstanding_invoices",
      "tax_deadlines",
      "client_count",
      "billable_hours",
    ],
    feature_flags: {
      time_tracking: true,
      tax_reports: true,
      recurring_invoices: true,
    },
  },

  restaurant: {
    label: "Restaurant / Cafe",
    icon: "🍽️",
    description: "Restaurants, cafes, food trucks, catering",
    theme: {
      primaryColor: "#dc2626",
      secondaryColor: "#f59e0b",
      accentColor: "#ea580c",
      sidebarColor: "#7f1d1d",
      theme: "red",
    },
    terminology: {
      customers: "Guests",
      customer: "Guest",
      products: "Menu Items",
      product: "Menu Item",
      services: "Specials",
      service: "Special",
      invoices: "Tabs",
      invoice: "Tab",
    },
    categories: [
      { name: "Appetizers", type: "product", color: "#f59e0b" },
      { name: "Mains", type: "product", color: "#dc2626" },
      { name: "Desserts", type: "product", color: "#ec4899" },
      { name: "Beverages", type: "product", color: "#06b6d4" },
    ],
    custom_fields: [
      {
        entity_type: "product",
        field_name: "ingredients",
        field_label: "Ingredients",
        field_type: "textarea",
      },
      {
        entity_type: "product",
        field_name: "allergens",
        field_label: "Allergens",
        field_type: "text",
      },
      {
        entity_type: "product",
        field_name: "is_vegetarian",
        field_label: "Vegetarian",
        field_type: "checkbox",
      },
    ],
    dashboard_widgets: [
      "sales_today",
      "top_dishes",
      "tables_occupied",
      "revenue_month",
    ],
    feature_flags: { pos: true, table_management: true, kitchen_display: true },
  },

  freelancer: {
    label: "Freelancer / Consultant",
    icon: "💻",
    description: "Solo freelancers, consultants, designers, developers",
    theme: {
      primaryColor: "#6366f1",
      secondaryColor: "#8b5cf6",
      accentColor: "#06b6d4",
      sidebarColor: "#1e1b4b",
      theme: "indigo",
    },
    terminology: {
      customers: "Clients",
      customer: "Client",
      products: "Deliverables",
      product: "Deliverable",
      services: "Projects",
      service: "Project",
      invoices: "Invoices",
      invoice: "Invoice",
    },
    categories: [
      { name: "Design", type: "service", color: "#ec4899" },
      { name: "Development", type: "service", color: "#6366f1" },
      { name: "Consulting", type: "service", color: "#10b981" },
      { name: "Hourly", type: "service", color: "#f59e0b" },
    ],
    custom_fields: [
      {
        entity_type: "service",
        field_name: "hourly_rate",
        field_label: "Hourly Rate",
        field_type: "number",
      },
      {
        entity_type: "service",
        field_name: "project_status",
        field_label: "Status",
        field_type: "select",
        options: ["Proposed", "Active", "On Hold", "Completed"],
      },
      {
        entity_type: "customer",
        field_name: "project_brief",
        field_label: "Project Brief",
        field_type: "textarea",
      },
    ],
    dashboard_widgets: [
      "active_projects",
      "outstanding_invoices",
      "revenue_month",
      "hours_logged",
    ],
    feature_flags: { time_tracking: true, recurring_invoices: true },
  },

  realestate: {
    label: "Real Estate",
    icon: "🏠",
    description: "Real estate agents, property managers, brokers",
    theme: {
      primaryColor: "#0d9488",
      secondaryColor: "#0891b2",
      accentColor: "#14b8a6",
      sidebarColor: "#134e4a",
      theme: "teal",
    },
    terminology: {
      customers: "Clients",
      customer: "Client",
      products: "Properties",
      product: "Property",
      services: "Services",
      service: "Service",
      invoices: "Commissions",
      invoice: "Commission",
    },
    categories: [
      { name: "Residential", type: "product", color: "#0d9488" },
      { name: "Commercial", type: "product", color: "#0891b2" },
      { name: "Rental", type: "product", color: "#10b981" },
      { name: "Land", type: "product", color: "#f59e0b" },
    ],
    custom_fields: [
      {
        entity_type: "product",
        field_name: "property_type",
        field_label: "Property Type",
        field_type: "select",
        options: ["House", "Apartment", "Condo", "Land", "Commercial"],
      },
      {
        entity_type: "product",
        field_name: "bedrooms",
        field_label: "Bedrooms",
        field_type: "number",
      },
      {
        entity_type: "product",
        field_name: "bathrooms",
        field_label: "Bathrooms",
        field_type: "number",
      },
      {
        entity_type: "product",
        field_name: "square_feet",
        field_label: "Square Feet",
        field_type: "number",
      },
      {
        entity_type: "product",
        field_name: "address",
        field_label: "Address",
        field_type: "textarea",
      },
    ],
    dashboard_widgets: [
      "active_listings",
      "pending_deals",
      "commissions_month",
      "leads",
    ],
    feature_flags: { listings: true, mls: true },
  },

  salon: {
    label: "Salon / Beauty",
    icon: "💇",
    description: "Hair salons, spas, beauty parlors, nail studios",
    theme: {
      primaryColor: "#d946ef",
      secondaryColor: "#ec4899",
      accentColor: "#f472b6",
      sidebarColor: "#581c87",
      theme: "fuchsia",
    },
    terminology: {
      customers: "Clients",
      customer: "Client",
      products: "Products",
      product: "Product",
      services: "Services",
      service: "Service",
      invoices: "Bills",
      invoice: "Bill",
    },
    categories: [
      { name: "Hair", type: "service", color: "#d946ef" },
      { name: "Skin", type: "service", color: "#ec4899" },
      { name: "Nails", type: "service", color: "#f472b6" },
      { name: "Spa", type: "service", color: "#a855f7" },
      { name: "Hair Products", type: "product", color: "#8b5cf6" },
    ],
    custom_fields: [
      {
        entity_type: "service",
        field_name: "duration",
        field_label: "Duration (min)",
        field_type: "number",
      },
      {
        entity_type: "customer",
        field_name: "preferences",
        field_label: "Preferences",
        field_type: "textarea",
      },
      {
        entity_type: "customer",
        field_name: "last_visit",
        field_label: "Last Visit",
        field_type: "date",
      },
    ],
    dashboard_widgets: [
      "appointments_today",
      "revenue_month",
      "top_services",
      "client_retention",
    ],
    feature_flags: { appointments: true, loyalty: true },
  },

  general: {
    label: "Other / General Business",
    icon: "🏢",
    description: "I'll set things up myself",
    theme: {
      primaryColor: "#6366f1",
      secondaryColor: "#8b5cf6",
      accentColor: "#06b6d4",
      sidebarColor: "#1e1b4b",
      theme: "indigo",
    },
    terminology: {},
    categories: [],
    custom_fields: [],
    dashboard_widgets: [
      "revenue_month",
      "customer_count",
      "top_products",
      "pending_invoices",
    ],
    feature_flags: {},
  },
};

function listPresets() {
  return Object.entries(PRESETS).map(([key, p]) => ({
    key,
    label: p.label,
    icon: p.icon,
    description: p.description,
  }));
}

function getPreset(key) {
  return PRESETS[key] || null;
}

module.exports = { PRESETS, listPresets, getPreset };
